# -*- coding: utf-8 -*-
"""Lab Session  -  E-Commerce (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18f71VQ8OqmNdxzd7lMx8nszYx2IU0mAH

# Lab Session

## <font color='blue'> Table Of Contents </font>
- Problem Statement
- Load required libraries
- Connect to DB using mysql-connector-python package
- Create database named `e_commerce`
- Create tables and insert data into tables as specified in the question
- Read all the questions and write sql queries to meet the objective

## <font color='blue'> Problem Statement </font>
###  An E-commerce website manages its data in the form of various tables.
You need to create a Database called `e_commerce` and various tables in it. The tables needed and attributes which need to be in every table are given before hand. All you have to do is create tables with data in it and answer some of the questions that follows.

### e_commerce Schema:

![e_commerce%20_schema.png](attachment:e_commerce%20_schema.png)

### Load Required Libraries
"""



"""### Connect to DB using Mysql-connector-python package"""



"""### You are required to create a database named 'e_commerce'"""



"""### Q1. Create tables for supplier, customer, category, product, productDetails, order, rating to store the data for the E-commerce with the schema definition given below.


- **`supplier`**(SUPP_ID int primary key, SUPP_NAME varchar(50), SUPP_CITY varchar(50), SUPP_PHONE varchar(10))


- **`customer`** (CUS_ID INT NOT NULL, CUS_NAME VARCHAR(20) NULL DEFAULT NULL, CUS_PHONE VARCHAR(10), CUS_CITY varchar(30) ,CUS_GENDER CHAR,PRIMARY KEY (CUS_ID))


- **`category`** (CAT_ID INT NOT NULL, CAT_NAME VARCHAR(20) NULL DEFAULT NULL,PRIMARY KEY (CAT_ID))


- **`product`** (PRO_ID INT NOT NULL, PRO_NAME VARCHAR(20) NULL DEFAULT NULL, PRO_DESC VARCHAR(60) NULL DEFAULT NULL, CAT_ID INT NOT NULL,PRIMARY KEY (PRO_ID),FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (CAT_ID))


- **`product_details`** (PROD_ID INT NOT NULL, PRO_ID INT NOT NULL, SUPP_ID INT NOT NULL, PROD_PRICE INT NOT NULL,
  PRIMARY KEY (PROD_ID),FOREIGN KEY (PRO_ID) REFERENCES PRODUCT (PRO_ID), FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPP_ID))
  
  
- **`order`** (ORD_ID INT NOT NULL, ORD_AMOUNT INT NOT NULL, ORD_DATE DATE, CUS_ID INT NOT NULL, PROD_ID INT NOT NULL,PRIMARY KEY (ORD_ID),FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),FOREIGN KEY (PROD_ID) REFERENCES PRODUCT_DETAILS(PROD_ID))


- **`rating`** (RAT_ID INT NOT NULL, CUS_ID INT NOT NULL, SUPP_ID INT NOT NULL, RAT_RATSTARS INT NOT NULL,PRIMARY KEY (RAT_ID),FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER (SUPP_ID),FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID))
"""

CREATE TABLE supplier (
    SUPP_ID INT PRIMARY KEY,
    SUPP_NAME VARCHAR(50),
    SUPP_CITY VARCHAR(50),
    SUPP_PHONE VARCHAR(10)
);

CREATE TABLE customer (
    CUS_ID INT PRIMARY KEY,
    CUS_NAME VARCHAR(20) DEFAULT NULL,
    CUS_PHONE VARCHAR(10),
    CUS_CITY VARCHAR(30),
    CUS_GENDER CHAR(1)
);

CREATE TABLE category (
    CAT_ID INT PRIMARY KEY,
    CAT_NAME VARCHAR(20) DEFAULT NULL
);

CREATE TABLE product (
    PRO_ID INT PRIMARY KEY,
    PRO_NAME VARCHAR(20) DEFAULT NULL,
    PRO_DESC VARCHAR(60) DEFAULT NULL,
    CAT_ID INT,
    FOREIGN KEY (CAT_ID) REFERENCES category (CAT_ID)
);

CREATE TABLE product_details (
    PROD_ID INT PRIMARY KEY,
    PRO_ID INT,
    SUPP_ID INT,
    PROD_PRICE INT,
    FOREIGN KEY (PRO_ID) REFERENCES product (PRO_ID),
    FOREIGN KEY (SUPP_ID) REFERENCES supplier (SUPP_ID)
);

CREATE TABLE orders (
    ORD_ID INT PRIMARY KEY,
    ORD_AMOUNT INT,
    ORD_DATE DATE,
    CUS_ID INT,
    PROD_ID INT,
    FOREIGN KEY (CUS_ID) REFERENCES customer (CUS_ID),
    FOREIGN KEY (PROD_ID) REFERENCES product_details (PROD_ID)
);

CREATE TABLE rating (
    RAT_ID INT PRIMARY KEY,
    CUS_ID INT,
    SUPP_ID INT,
    RAT_RATSTARS INT,
    FOREIGN KEY (SUPP_ID) REFERENCES supplier (SUPP_ID),
    FOREIGN KEY (CUS_ID) REFERENCES customer (CUS_ID)
);

"""### Q2. Insert the following data in the table created above
#### `Note:` If you are getting any error while inserting the data into tables, Kindly close the connection and reconnect

#### Table:  supplier
| SUPP_ID | SUPP_NAME | SUPP_CITY | SUPP_PHONE |
| --- | --- | --- | --- |
| 1 | Rajesh Retails | Delhi | 1234567890 |
| 2 | Appario Ltd. | Mumbai | 258963147032 |
| 3 | Knome products | Bangalore | 9785462315 |
| 4 | Bansal Retails | Kochi | 8975463285 |
| 5 | Mittal Ltd. | Lucknow | 7898456532 |
"""

-- Insert data into supplier
INSERT INTO supplier (SUPP_ID, SUPP_NAME, SUPP_CITY, SUPP_PHONE) VALUES
(1, 'Rajesh Retails', 'Delhi', '1234567890'),
(2, 'Appario Ltd.', 'Mumbai', '2589631470'),
(3, 'Knome products', 'Bangalore', '9785462315'),
(4, 'Bansal Retails', 'Kochi', '8975463285'),
(5, 'Mittal Ltd.', 'Lucknow', '7898456532');

-- Insert data into customer
INSERT INTO customer (CUS_ID, CUS_NAME, CUS_PHONE, CUS_CITY, CUS_GENDER) VALUES
(1, 'AAKASH', '9999999999', 'DELHI', 'M'),
(2, 'AMAN', '9785463215', 'NOIDA', 'M'),
(3, 'NEHA', '9999999998', 'MUMBAI', 'F'),
(4, 'MEGHA', '9994562399', 'KOLKATA', 'F'),
(5, 'PULKIT', '7895999999', 'LUCKNOW', 'M');

-- Insert data into category
INSERT INTO category (CAT_ID, CAT_NAME) VALUES
(1, 'BOOKS'),
(2, 'GAMES'),
(3, 'GROCERIES'),
(4, 'ELECTRONICS'),
(5, 'CLOTHES');

-- Insert data into product
INSERT INTO product (PRO_ID, PRO_NAME, PRO_DESC, CAT_ID) VALUES
(1, 'GTA V', 'DFJDJFDJFDJFDJFJF', 2),
(2, 'TSHIRT', 'DFDFJDFJDKFD', 5),
(3, 'ROG LAPTOP', 'DFNTTNTNTERND', 4),
(4, 'OATS', 'REURENTBTOTH', 3),
(5, 'HARRY POTTER', 'NBEMCTHTJTH', 1);

-- Insert data into product_details
INSERT INTO product_details (PROD_ID, PRO_ID, SUPP_ID, PROD_PRICE) VALUES
(1, 1, 2, 1500),
(2, 3, 5, 30000),
(3, 5, 1, 3000),
(4, 2, 3, 2500),
(5, 4, 1, 1000);

-- Insert data into orders
INSERT INTO orders (ORD_ID, ORD_AMOUNT, ORD_DATE, CUS_ID, PROD_ID) VALUES
(20, 1500, '2021-10-12', 3, 5),
(25, 30500, '2021-09-16', 5, 2),
(26, 2000, '2021-10-05', 1, 1),
(30, 3500, '2021-08-16', 4, 3),
(50, 2000, '2021-10-06', 2, 1);

-- Insert data into rating
INSERT INTO rating (RAT_ID, CUS_ID, SUPP_ID, RAT_RATSTARS) VALUES
(1, 2, 2, 4),
(2, 3, 4, 3),
(3, 5, 1, 5),
(4, 1, 3, 2),
(5, 4, 5, 4);

"""#### Table:  customer
| CUS_ID | CUS_NAME | SUPP_PHONE | CUS_CITY | CUS_GENDER
| --- | --- | --- | --- | --- |
| 1 | AAKASH | 9999999999 | DELHI | M |
| 2 | AMAN | 9785463215 | NOIDA | M |
| 3 | NEHA | 9999999998 | MUMBAI | F |
| 4 | MEGHA | 9994562399 | KOLKATA | F |
| 5 | PULKIT | 7895999999 | LUCKNOW | M |
"""

# insert into "customer" table

"""#### Table:  category
| CAT_ID | CAT_NAME |
| --- | --- |  
| 1 | BOOKS |
| 2 | GAMES |  
| 3 | GROCERIES |
| 4 | ELECTRONICS |
| 5 | CLOTHES |
"""

# insert into "categoty" table

"""#### Table:  product
| PRO_ID | PRO_NAME | PRO_DESC | CAT_ID |
| --- | --- | --- | --- |
| 1 | GTA V | DFJDJFDJFDJFDJFJF | 2 |
| 2 | TSHIRT | DFDFJDFJDKFD | 5 |
| 3 | ROG LAPTOP | DFNTTNTNTERND | 4 |
| 4 | OATS | REURENTBTOTH | 3 |
| 5 | HARRY POTTER | NBEMCTHTJTH | 1 |

"""

# insert into "product" table

"""#### Table:  product_details
| PROD_ID | PRO_ID | SUPP_ID | PROD_PRICE |
| --- | --- | --- | --- |
| 1 | 1 | 2 | 1500 |
| 2 | 3 | 5 | 30000 |
| 3 | 5 | 1 | 3000 |
| 4 | 2 | 3 | 2500 |
| 5 | 4 | 1 | 1000 |
"""

# insert into "product_details" table

"""#### Table:  orders
| ORD_ID | ORD_AMOUNT | ORD_DATE | CUS_ID | PROD_ID
| --- | --- | --- | --- | --- |
| 20 | 1500 | 2021-10-12 | 3 | 5 |
| 25 | 30500 | 2021-09-16 | 5 | 2 |
| 26 | 2000 | 2021-10-05 | 1 | 1 |
| 30 | 3500 | 2021-08-16 | 4 | 3 |
| 50 | 2000 | 2021-10-06 | 2 | 1 |
"""

# insert into "orders" table

"""#### Table: rating
| RAT_ID | CUS_ID | SUPP_ID | RAT_RATSTARS |
| --- | --- | --- | --- |
| 1 | 2 | 2 | 4 |
| 2 | 3 | 4 | 3 |
| 3 | 5 | 1 | 5 |
| 4 | 1 | 3 | 2 |
| 5 | 4 | 5 | 4 |
"""

# insert into "rating" table

"""### Q3) Display the number of the customer group by their genders who have placed any order of amount greater than or equal to Rs.3000."""

SELECT CUS_GENDER, COUNT(*) AS NumberOfCustomers
FROM customer c
JOIN orders o ON c.CUS_ID = o.CUS_ID
WHERE o.ORD_AMOUNT >= 3000
GROUP BY CUS_GENDER;

"""### Q4) Display all the order along with product name ordered by a customer having Customer_Id=2;"""

SELECT o.ORD_ID, o.ORD_AMOUNT, o.ORD_DATE, p.PRO_NAME
FROM orders o
JOIN product_details pd ON o.PROD_ID = pd.PROD_ID
JOIN product p ON pd.PRO_ID = p.PRO_ID
WHERE o.CUS_ID = 2;

"""### Q5) Display the Supplier details who can supply more than one product."""

SELECT s.SUPP_ID, s.SUPP_NAME, s.SUPP_CITY, s.SUPP_PHONE
FROM supplier s
JOIN product_details pd ON s.SUPP_ID = pd.SUPP_ID
GROUP BY s.SUPP_ID, s.SUPP_NAME, s.SUPP_CITY, s.SUPP_PHONE
HAVING COUNT(pd.PROD_ID) > 1;

"""### Q6) Find the category of the product whose order amount is minimum."""

SELECT c.CAT_NAME
FROM orders o
JOIN product_details pd ON o.PROD_ID = pd.PROD_ID
JOIN product p ON pd.PRO_ID = p.PRO_ID
JOIN category c ON p.CAT_ID = c.CAT_ID
ORDER BY o.ORD_AMOUNT ASC
LIMIT 1;

"""### Q7) Display the Id and Name of the Product ordered after “2021-10-05”."""

SELECT DISTINCT p.PRO_ID, p.PRO_NAME
FROM orders o
JOIN product_details pd ON o.PROD_ID = pd.PROD_ID
JOIN product p ON pd.PRO_ID = p.PRO_ID
WHERE o.ORD_DATE > '2021-10-05';

"""### Q8) Print the top 3 supplier name and id and rating on the basis of their rating along with the customer name who has given the rating."""

SELECT s.SUPP_ID, s.SUPP_NAME, r.RAT_RATSTARS, c.CUS_NAME
FROM rating r
JOIN supplier s ON r.SUPP_ID = s.SUPP_ID
JOIN customer c ON r.CUS_ID = c.CUS_ID
ORDER BY r.RAT_RATSTARS DESC
LIMIT 3;

"""### Q9) Display customer name and gender whose names start or end with character 'A'."""

SELECT CUS_NAME, CUS_GENDER
FROM customer
WHERE CUS_NAME LIKE 'A%' OR CUS_NAME LIKE '%A';

"""### Q10) Display the total order amount of the male customers."""

SELECT SUM(o.ORD_AMOUNT) AS TotalOrderAmount
FROM orders o
JOIN customer c ON o.CUS_ID = c.CUS_ID
WHERE c.CUS_GENDER = 'M';

"""### Q11) Display all the Customers left outer join with  the orders"""

SELECT c.*, o.*
FROM customer c
LEFT JOIN orders o ON c.CUS_ID = o.CUS_ID;

"""**NOTE:** Always close an open connection once you are done with the database operations

## Happy Learning:)
"""